export interface TestResultItem {
  testCase: string;
  techniqueId: string;
  technique: string;
  phase: string;
  outcome: string;
  tactic: string;
}

export const testedResults: TestResultItem[] = [
  {
    testCase: "Discover AD Server",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1018",
    technique: "Remote System Discovery",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Create SMB session to AD Server",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "None",
  },
  {
    testCase: "Transfer RAT Agent_1",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "None",
  },
  {
    testCase: "Execute RAT Agent_1",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "None",
  },
  {
    testCase: "Discover C-ITS Operator",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1087.002",
    technique: "Account Discovery : Domain Account",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Create SMB session to C-ITS Operator",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "None",
  },
  {
    testCase: "Transfer RAT Agent_2",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "None",
  },
  {
    testCase: "Execute RAT Agent_2",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "None",
  },
  {
    testCase: "Credential Dumping(MimiKatz)",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1003.001",
    technique: "OS Credential Dumping : LSASS Memory",
    tactic: "Credential-Dumping",
    outcome: "None",
  },
  {
    testCase: "Read Dumped Credentials",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1003.001",
    technique: "OS Credential Dumping : LSASS Memory",
    tactic: "Credential-Dumping",
    outcome: "None",
  },
  {
    testCase: "Brute-Force Dumped Credentials",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1110",
    technique: "Brute Force",
    tactic: "Credential-Dumping",
    outcome: "None",
  },
  {
    testCase: "Discover RSU-Manage-Server",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1018",
    technique: "Remote System Discovery",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Lateral Movement to RSU-Manage-Server",
    phase: "Penetration to C-ITS Center (Q1)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "None",
  },
  {
    testCase: "Discover AD Server",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1018",
    technique: "Remote System Discovery",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Create SMB session to AD Server",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "None",
  },
  {
    testCase: "Transfer RAT Agent_1",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Logged",
  },
  {
    testCase: "Execute RAT Agent_1",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Logged",
  },
  {
    testCase: "Discover C-ITS Operator",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1087.002",
    technique: "Account Discovery : Domain Account",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Create SMB session to C-ITS Operator",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "None",
  },
  {
    testCase: "Transfer RAT Agent_2",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Logged",
  },
  {
    testCase: "Execute RAT Agent_2",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Logged",
  },
  {
    testCase: "Credential Dumping(MimiKatz)",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1003.001",
    technique: "OS Credential Dumping : LSASS Memory",
    tactic: "Credential-Dumping",
    outcome: "Logged",
  },
  {
    testCase: "Read Dumped Credentials",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1003.001",
    technique: "OS Credential Dumping : LSASS Memory",
    tactic: "Credential-Dumping",
    outcome: "None",
  },
  {
    testCase: "Brute-Force Dumped Credentials",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1110",
    technique: "Brute Force",
    tactic: "Credential-Dumping",
    outcome: "None",
  },
  {
    testCase: "Discover RSU-Manage-Server",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1018",
    technique: "Remote System Discovery",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Lateral Movement to RSU-Manage-Server",
    phase: "Penetration to C-ITS Center (Q2)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Logged",
  },
  {
    testCase: "Discover AD Server",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1018",
    technique: "Remote System Discovery",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Create SMB session to AD Server",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Logged",
  },
  {
    testCase: "Transfer RAT Agent_1",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Alert",
  },
  {
    testCase: "Execute RAT Agent_1",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Alert",
  },
  {
    testCase: "Discover C-ITS Operator",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1087.002",
    technique: "Account Discovery : Domain Account",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Create SMB session to C-ITS Operator",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Logged",
  },
  {
    testCase: "Transfer RAT Agent_2",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Alert",
  },
  {
    testCase: "Execute RAT Agent_2",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Alert",
  },
  {
    testCase: "Credential Dumping(MimiKatz)",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1003.001",
    technique: "OS Credential Dumping : LSASS Memory",
    tactic: "Credential-Dumping",
    outcome: "Alert",
  },
  {
    testCase: "Read Dumped Credentials",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1003.001",
    technique: "OS Credential Dumping : LSASS Memory",
    tactic: "Credential-Dumping",
    outcome: "Logged",
  },
  {
    testCase: "Brute-Force Dumped Credentials",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1110",
    technique: "Brute Force",
    tactic: "Credential-Dumping",
    outcome: "Logged",
  },
  {
    testCase: "Discover RSU-Manage-Server",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1018",
    technique: "Remote System Discovery",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Lateral Movement to RSU-Manage-Server",
    phase: "Penetration to C-ITS Center (Q3)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Alert",
  },
  {
    testCase: "Discover AD Server",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1018",
    technique: "Remote System Discovery",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Create SMB session to AD Server",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Logged",
  },
  {
    testCase: "Transfer RAT Agent_1",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Alert",
  },
  {
    testCase: "Execute RAT Agent_1",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Alert",
  },
  {
    testCase: "Discover C-ITS Operator",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1087.002",
    technique: "Account Discovery : Domain Account",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Create SMB session to C-ITS Operator",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Logged",
  },
  {
    testCase: "Transfer RAT Agent_2",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1021.002",
    technique: "Remote Services: SMB/Windows Admin Shares",
    tactic: "Lateral-movement",
    outcome: "Alert",
  },
  {
    testCase: "Execute RAT Agent_2",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Alert",
  },
  {
    testCase: "Credential Dumping(MimiKatz)",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1003.001",
    technique: "OS Credential Dumping : LSASS Memory",
    tactic: "Credential-Dumping",
    outcome: "Alert",
  },
  {
    testCase: "Read Dumped Credentials",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1003.001",
    technique: "OS Credential Dumping : LSASS Memory",
    tactic: "Credential-Dumping",
    outcome: "Alert",
  },
  {
    testCase: "Brute-Force Dumped Credentials",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1110",
    technique: "Brute Force",
    tactic: "Credential-Dumping",
    outcome: "Alert",
  },
  {
    testCase: "Discover RSU-Manage-Server",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1018",
    technique: "Remote System Discovery",
    tactic: "Discovery",
    outcome: "None",
  },
  {
    testCase: "Lateral Movement to RSU-Manage-Server",
    phase: "Penetration to C-ITS Center (Q4)",
    techniqueId: "T1569.002",
    technique: "System Services: Service Execution",
    tactic: "Execution",
    outcome: "Alert",
  },
];
